app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::get('institucion', ['middleware' => 'auth', 'uses' => 'InstitucionController@index', 'as' => 'institucion.index']);
Route::get('institucion/create',['middleware' => 'administrador', 'uses'=>'InstitucionController@create', 'as' => 'institucion.create']);

Route::get('institucion/{id}/edit', ['middleware' => 'coordinador', 'middleware' => 'administrador','uses' => 'InstitucionController@edit', 'as' => 'institucion.edit']);

Route::get('institucion/{id}', ['middleware' => 'auth', 'uses' => 'InstitucionController@show', 'as' => 'institucion.show']);

Route::post('institucion', ['uses' => 'InstitucionController@store', 'as' => 'institucion.store']);
Route::patch('institucion/{id}', ['uses' => 'InstitucionController@update', 'as' => 'institucion.update']);
Route::put('institucion/{id}', [
    'as' => 'institucion.update', 'uses' => 'InstitucionController@update'
]);
Route::get('instituciondestro/{id}/',['middleware' => 'administrador', 'uses' => 'InstitucionController@destroy']);


Route::resource('actividad', 'ActividadController');
Route::resource('coordinador', 'CoordinadorController');

Route::get('actividad/{id}/destroy', ['uses' => 'ActividadController@destroy', 'as' => 'actividad.destroy']);

Route::get('coordinador/{id}/destroy', ['uses' => 'CoordinadorController@destroy', 'as' => 'coordinador.destroy']);


Route::resource('convenio', 'ConvenioController');
Route::auth();

/*Solo el admin puede hacer estas acciones*/
Route::get('convenio/{id}/destroy', ['uses' => 'ConvenioController@destroy', 'as' => 'convenio.destroy']);
Route::resource('modalidad', 'ModalidadConvenioController');
Route::get('modalidad/{id}/destroy', ['uses' => 'ModalidadConvenioController@destroy', 'as' => 'modalidad.destroy']);
Route::resource('estado', 'EstadoConvenioController');
Route::get('estado/{id}/destroy', ['uses' => 'EstadoConvenioController@destroy', 'as' => 'estado.destroy']);

resources/views/estado/create.blade.php
@extends('welcome')
@section('titulo','Registrar estado de convenio')

@section('contenido')

<div class="principal">
            <h1 class="titleform">Registrar estado de convenio</h1>
            <div class="linetitle"></div>

            {{ Form::open(['route' => 'estado.store',  'method' => 'POST','class'=>'formulario']) }}
            <div class="form-2">
                {{ Form::label('nombre_estado_convenio', 'Nombre de estado',['class'=>'form-label']) }}
                {{ Form::text('nombre_estado_convenio', null, ['class' => 'form-text'])}}
            </div>    

            <div class="form-2">
                {{ Form::label('descripcion', 'Descripcion',['class'=>'form-label']) }}
                {{ Form::text('descripcion', null, ['class' => 'form-text'])}}
            </div>

            <div class="form-2">
                {{ Form::label('vigente', 'Vigente',['class'=>'form-label']) }} 
                {{ Form::select('vigente', ['1' => 'Si', '0' => 'No'], null, ['class' => 'form-text', 'placeholder' => 'Seleccione una opción']) }} 
            </div>

            <div class="form-group">
                {{ Form::submit('Guardar',['class'=>'btn-submit']) }}
            </div>

            {{ Form::close()}}
            </div>
            </div>

</div>
@endsection

resources/views/estado/edit.blade.php
@extends('welcome')
@section('titulo','Editar estado de convenio')

@section('contenido')

<div class="principal">
            <h1 class="titleform">Editar estado de convenio</h1>
            <div class="linetitle"></div>
            {{ Form::open(['route' => ['estado.update',$estado],  'method' => 'PUT','class'=>'formulario']) }}            
            <div class="form-2">
                {{ Form::label('nombre_estado_convenio', 'Nombre de estado de convenio',['class'=>'form-label']) }}
                {{ Form::text('nombre_estado_convenio', $estado->nombre_estado_convenio, ['class' => 'form-text'])}}
            </div>               

            <div class="form-2">
                {{ Form::label('descripcion', 'Descripcion',['class'=>'form-label']) }}
                {{ Form::text('descripcion', $estado->descripcion, ['class' => 'form-text'])}}
            </div>

            <div class="form-2">
                {{ Form::label('vigente', 'Vigente',['class'=>'form-label']) }}
                {{ Form::select('vigente', ['1' => 'Si', '0' => 'No'], $estado->vigente, ['class' => 'form-text', 'placeholder' => 'Seleccione una opción']) }}                
            </div>

            <div class="form-group">
                {{ Form::submit('Guardar',['class'=>'btn-submit']) }}
            </div>
                    {{ Form::close()}}
                </div>
            </div>            
</div>
@endsection

resources/views/estado/index.blade.php
@extends('welcome')
@section('contenido')
<div class="principal">            
            <div class="div-group-3-btn">
                <a href="{{ route('estado.create') }}" class="btn-principal">Agregar estado</a>
            </div>
            <h1 class="titleform">Estados de convenio</h1>
            <div class="linetitle"></div>
    <br><br>
    <table class="table">
                    <thead>
                        <tr class="encabezado-tabla">
                            <th>ID</th>
                            <th>Nombre de estado de convenio</th>
                            <th>Descripcion</th>
                            <th>Vigente</th>
                            <th>Editar</th>   
                            <th>Eliminar</th>   
                        </tr> 
                    </thead>
                    <tbody>
                    @if(count($estados)>0)
                        @foreach($estados as $estado)
                            <tr class="table-color">
                                <td class="td-tabla">{{$estado->id}}</td>                               
                                <td class="td-tabla">{{$estado->nombre_estado_convenio}}</td>
                                <td class="td-tabla">{{$estado->descripcion}}</td>
                                @if($estado->vigente==1)
                                    <td class="td-tabla">Sí</td>
                                @else
                                    <td class="td-tabla">No</td>
                                @endif                               

                                <td class="td-tabla"><a href="{{ route('estado.edit', $estado->id) }}" class="btn btn-warning">
                                    <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a></td>

                                <td class="td-tabla"><a href="{{ route('estado.destroy', $estado->id) }}" class="btn btn-danger" onclick="return confirm('Eliminar')"> <span class="glyphicon glyphicon-trash" aria-hidden="true"></span></a></td>
                            </tr>
                            @endforeach
                    @else
                    <div class="tabla-vacia">
                        <p>Sin convenios</p>
                    </div>
                    
                    @endif
                    </tbody>
        </table>

</div>
@endsection